apiVersion: v1
kind: Secret
metadata:
  name: git-ssh  # `git-ssh` is the default name.
                        #   - operators can change such default by using the
                        #     `gitops.ssh_secret` property in `tap-values.yaml`
                        #   - developers can override by using the workload parameter
                        #     named `gitops_ssh_secret`.
  annotations:
    tekton.dev/git-0: https://github.com # ! required
type: kubernetes.io/basic-auth          # ! required
stringData:
  username: $repo_owner
  password: $git_token 
